### ISSUE TITLE
Transient only working the first time with starship

### ISSUE THREAD

**Issue by franroa** [zzhaolei/transient-prompt.fish#10]
Hi there! very nice plugin.
I facing a issue with startship and transient.

the first command is working properly: it erases the old prompt. But from then on, it makes no changes and all old prompts remain.

I am installing starship in the fish_prompt function like this:

source (starship init fish --print-full-init | psub)

**Comment by zzhaolei** [comment]
I'm OK.

<img width="598" alt="image" src="https://github.com/zzhaolei/transient.fish/assets/17561793/8c82e3ac-9a20-4db1-8ada-b8c1552833dc">

bat ~/.config/fish/config.fish:
```fish
# ...
source (starship init fish --print-full-init | psub)
```

fisher list:
```
jorgebucaran/fisher
jethrokuan/fzf
patrickf1/colored_man_pages.fish
jhillyerd/plugin-git
jethrokuan/z
zzhaolei/tldr.fish
zzhaolei/auto-venv.fish
jorgebucaran/autopair.fish
zzhaolei/transient.fish
jorgebucaran/hydro
```

**Comment by zzhaolei** [comment]
Try running `fisher update`

**Comment by franroa** [comment]
Not working for me..
It used to work on my previous set up, but I have installed everything new and is not working. These are my versions:

![Capture](https://github.com/zzhaolei/transient.fish/assets/2432583/06cce830-9330-4ce7-b643-a3191b297ece)

**Comment by franroa** [comment]
only the first command works

**Comment by zzhaolei** [comment]
Try reinstalling?

**Comment by franroa** [comment]
I worked reinstalling fish.
Thanks!
