### ISSUE TITLE
The config information of your fish

### ISSUE THREAD

**Issue by YadongM** [zzhaolei/transient-prompt.fish#8]
**Sorry for creating an issue**

First of all, thank you for your work!
Then I found your fish to be beautiful, especially the icons and colors.
Could you share the configuration information of your fish?
Thank you in advance!

**Comment by zzhaolei** [comment]
Config list:
```
Prompt: starship
Prompt theme: starship preset tokyo-night
Font && Icons: github.com/epk/SF-Mono-Nerd-Font
```

**Comment by RedemptionC** [comment]
thanks !  it does look great. 
but there's a problem with my config
![image](https://github.com/zzhaolei/transient.fish/assets/17563754/db4fb4e1-e015-4689-8453-adc2855924f8)

the vim mode icon was displayed in a separate line, how can we fix this?

**Comment by zzhaolei** [comment]
editor `~/.config/fish/functions/fish_mode_prompt.fish` or `~/.config/fish/config.fish`, add:
```
function fish_mode_prompt
end
```
