### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by iynaix** [zzhaolei/transient-prompt.fish#9]
Hi, I would like to package this fish plugin for NixOS and was wondering what the license was? Could you add a license? I would rather not classify it as "unfree". Thanks!

**Comment by zzhaolei** [comment]
I don't know much about license. How about using the "MIT License"?

**Comment by iynaix** [comment]
Sounds good, could you add the [LICENSE file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)? Thanks!

**Comment by zzhaolei** [comment]
MIT License added.
